package com.sad.code.solutions;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
public class Euler2 {

    public static void main(String[] args) {
        long first = 1L;
        long second = 2L;
        long third = first + second;

        long result = 2L;

        while (true) {
            first = second;
            second = third;
            third = first + second;

            if (third % 2 == 0) {
                result += third;
            }

            if (third >= 4_000_000L) {
                System.out.println("Result: " + result);
                break;
            }
        }
    }
}
